### ISSUE TITLE
Deployment Question

### ISSUE THREAD

**Issue by zigzag414** [malcolmosh/dispatchPi#4]
Hi Malcolm - I was wondering if you had a suggestion for an issue I'm running into with the GCP environment. Been following the tutorial so far and have able to run the code locally and manually through the GCP shell. However when I get to the point of activating the Cloud APIs (gcloud services enable cloudbuild.googleapis.com etc.) the shell returns no messages like shown in the tutorial. It doesn't return anything at all. Same result when I set the environment variables as you show. I assume this is connected to the errors I then get when passing the docker image build commands which returns `ERROR: (gcloud.builds.submit) Invalid value for [source]: Dockerfile required when specifying --tag`

Thoughts?

**Comment by malcolmosh** [comment]
Hi! Thanks for trying out the tutorial. 

1. I fixed some formatting errors in the GCP command to activate those APIs - seems like the backslashes were causing errors. Can you try again with this following syntax in one line ? `gcloud services enable cloudbuild.googleapis.com containerregistry.googleapis.com run.googleapis.com`
2. Second, Try `gcloud services list --enabled` to see which services are active. Check to see whether the command to activate cloudbuild, the container registry and the cloud run admin API worked. Paste a screenshot of what you see. Otherwise, navigate to APIs & Services -> Enabled APIs & Services to see it in the GCP interface.
3. For the environment variable errors, try pasting them individually in the console to see if they succeeded even if you got no confirmation message. (For example, $TAG).
4. As for the dockerfile error, you have to be sure you're in the right directory so that the console can find the dockerfile. Does the $APP environment variable point to the folder you uploaded via the editor? Are you able to run the app when you point your console to that folder? Check that the $APP variable points to the correct folder.
5. Does your Dockerfile start with a capital D ? (See [here](https://stackoverflow.com/questions/72767352/gcloud-run-deploy-error-gcloud-run-deploy-invalid-value-for-source-dockerf))

**Comment by zigzag414** [comment]
The syntax changes seems to have done the trick for 1 and 2. 
![services2](https://github.com/malcolmosh/dispatchPi/assets/94332953/c0c44cb3-fd18-412b-a613-2c53da74b98a)

For 3, I checked and it appears the environment variables have taken correctly as well.

For the dockerfile error, I confirmed the directory is correct and it contains the docker file. I also updated the Dockerfile.py filename to a capital D. No change in the result unfortunately.
![docker2](https://github.com/malcolmosh/dispatchPi/assets/94332953/aee123a6-c9b9-445b-8ea0-87bb2303f7c2)

**Comment by malcolmosh** [comment]
Good news about the first command. 

I think I know the error here : your dockerfile should not have a .py extension. Rename it to remove ".py" and try again! A Dockerfile shouldn't have an extension.

**Comment by zigzag414** [comment]
Ah! I've learned so much through this. App is deployed and works like a charm. Thanks much!

**Comment by malcolmosh** [comment]
Good to know! Thanks for the comments :)
